### ISSUE TITLE
Support customised built-ins

### ISSUE THREAD

**Issue by bedeoverend** [skatejs/val#11]
Currently `val` treats `is` as an arbitrary prop, rather than as a special property to be passed to the constructor.

If you're happy to have it as a feature, I'm happy to make a PR, only thing is sane behavior. I _think_ treating it as an attribute rather than a prop would be best? Then let the `createElement` handle it as it sees fit? I believe that'll at least tell to create with React's `extends`, don't think Preact supports it at all.

**Comment by treshugart** [comment]
We don't have access to how React creates elements. We *might* with preact? I know it supports hooks.

I see the main things being:

1. Ensure we can extract built-in info from the constructor (storing this with the `define()` call so we can use it later).
2. Passing it through as an attribute (I think you're right about this).
3. Updating the default adapter for real DOM to use the stored info from number 1.

**Comment by bedeoverend** [comment]
Great! I'll put together a PR. Those points look good. I'll aim for that. 

I know if you just pass `is` prop to React, it'll pick it up and appropriately extend, so point 2 should address that if I'm understanding the point / the current src correctly. Looking in the src of Preact it doesn't _look_ like it supports extending, but I'll have an experiment and open an issue over there if needed.
