### ISSUE TITLE
Support React's Synthtic events

### ISSUE THREAD

**Issue by AndyOGo** [skatejs/val#26]
First this looks really great, I just tested it.
Before we tried https://github.com/skatejs/val/issues/react-integration, but that was broken.
Then we tried our own, unfortunately with bugs for `children`.
And yours really works great so far.

Except, it seems I can't use any of these:
https://reactjs.org/docs/events.html

**Note:** I know about the `events` object and can get it to work with it.
https://github.com/skatejs/val#events-and-custom-events

But I want to use also React's event system

**Comment by treshugart** [comment]
I can definitely [confirm](https://codesandbox.io/s/4q59m6v9lw) this bug. I [fixed](https://github.com/skatejs/val/tree/9079c69d54d1b81c81d1c998b92c06e5518883fd#dom-properties) it by making DOM `props` explicit, and passing through everything not in the special props, but there's a bug in `pikapkg` (pikapkg/pack#37) preventing me from releasing on my windows box right now. I'll try again on my Mac tomorrow.

**Comment by AndyOGo** [comment]
@treshugart 
Any updates, did you have a chance to release?
The bug of pikapkg/pack#37 is fixed,  right?

**Comment by treshugart** [comment]
Hey sorry for the delay. It's been published https://unpkg.com/@skatejs/val@0.5.0/.
