### ISSUE TITLE
dangerouslySetInnerHTML not working

### ISSUE THREAD

**Issue by tauren** [skatejs/val#8]
I'm using a library (MDXC) that converts markdown into JSX. It uses `dangerouslySetInnerHTML` to set the content within code fences ( ``` ) into `<pre><code>...</code></pre>` markup. It is doing something similar to this:

```js
createElement("pre", props, createElement("code", { dangerouslySetInnerHTML: { __html: children || props.children } }));
```

I'm altering the library to support `pragma` settings, which generates using `pragma h`:

```js
h("pre", props, h("code", { dangerouslySetInnerHTML: { __html: children || props.children } }));
```

I've imported `h` from the following module:

```js
import { createElement } from 'react'
import val from '@skatejs/val'
export default val(createElement)
```

The problem is that the resulting `<code>` block is empty, and I *think* it is because `val` is not passing the `dangerouslySetInnerHTML` property through to `createElement`.

**Comment by treshugart** [comment]
Happy to have this implemented. Would you mind sending over a PR?

**Comment by treshugart** [comment]
Also, sorry about the delay. Apparently I wasn't "watching" this repo.

**Comment by treshugart** [comment]
I think it's possible to get the `ref` and set `innerHTML` directly. Closing now as this has gotten a bit stale. LMK if that won't work for your purposes.
